src/Web/ViewModels/MainMenu.cs
namespace CALS.AgHallExport.Web.ViewModels
{
    /// <summary>
    /// View model used for the main menu
    /// </summary>
    public class MainMenu
    {
        public string LoggedInUser { get; set; }
    }
}

src/Web/Controllers/Api/AuthApiController.cs
using CALS.AgHallExport.Identity;
using CALS.AgHallExport.Web.Security;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CALS.AgHallExport.Web.Controllers.Api
{
    [Route("api/auth")]
    [ApiController]
    public class AuthApiController : ControllerBase
    {
        private readonly AppGroups _appGroups;
        public AuthApiController(AppGroups appGroups)
        {
            _appGroups = appGroups;
        }

        // GET: api/auth/groups
        /// <summary>
        /// Returns a listing of all system groups, and all groups that the logged-in user is a member of
        /// </summary>
        [ProducesResponseType(StatusCodes.Status200OK)]
        [HttpGet("groups", Name = "Auth_Groups")]
        public IActionResult GetGroups()
        {
            var user = AgHallExportUser.UserFromPrincipal(HttpContext.User);

            return Ok(new { system = _appGroups, user = user.Groups });
        }
    }
}

src/Web/Controllers/ErrorController.cs
using System;
using System.Threading.Tasks;
using AAE.Helpers.Email;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace AAE.Helpers.Errors
{

    public class ErrorController : Controller
    {
        private readonly IEmailSender _emailSender;

        public ErrorController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        [Route("~/error")]
        [Route("~/error/{statusCode:int}")]
        [AllowAnonymous]
        public async Task<IActionResult> Error(int? statusCode = null)
        {
            var model = new ErrorModel();

            if (statusCode == null)
                statusCode = HttpContext.Response.StatusCode;

            model.StatusCode = statusCode.Value;

            var feature = HttpContext.Features.Get<IStatusCodeReExecuteFeature>();

            // get routing data
            var endpointModel = EndpointExtractor.Extract(HttpContext);

            var request = HttpContext.Request;

            var errorModel = new ErrorEmailModel()
            {
                Query = request.Query,
                Cookies = request.Cookies,
                Headers = request.Headers,
                RouteValues = request.RouteValues,
                Endpoint = endpointModel,
                StatusCode = statusCode.Value,
                IpAddress = HttpContext.Connection.RemoteIpAddress.ToString(),
                UserId = "Unknown",
                Uri = new Uri($"{HttpContext.Request.Scheme}://{HttpContext.Request.Host}{feature?.OriginalPath}")
            };

            //string uaString = context.Request.Headers["User-Agent"].ToString();
            if (HttpContext.User.Identity.IsAuthenticated)
            {
                errorModel.UserId = HttpContext.User.Identity.Name;
            }

            var emailBody = ErrorEmailCreator.CreateStatusCodeEmail(errorModel);


            if (model.StatusCode != 500)
            {
                await _emailSender.SendAdminEmailAsync($"{statusCode.Value} Error: {errorModel.Uri}", emailBody);
            }


            return View(model);
        }

    }
}

src/Web/Controllers/HomeController.cs
using System;
using System.Threading.Tasks;
using CALS.AgHallExport.Interfaces;
using ClosedXML.Excel;
using DocumentFormat.OpenXml.Spreadsheet;
using Microsoft.AspNetCore.Mvc;

namespace CALS.AgHallExport.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IEpmExportQueries _epmExportQueries;
        private readonly IGGToolImportCreator _ggToolImport;

        public HomeController(IEpmExportQueries epmExportQueries, IGGToolImportCreator ggToolImport)
        {
            _ggToolImport = ggToolImport ?? throw new ArgumentNullException(nameof(ggToolImport));
            _epmExportQueries = epmExportQueries ?? throw new ArgumentNullException(nameof(epmExportQueries));
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet("export")]
        public async Task<IActionResult> Export()
        {

            // Response...
            System.Net.Mime.ContentDisposition cd = new System.Net.Mime.ContentDisposition
            {
                FileName = $"AgHall_{DateTime.Now:yyyyMMdd}.csv",
                Inline = false  // false = prompt the user for downloading;  true = browser to try to show the file inline
            };
            Response.Headers.Add("Content-Disposition", cd.ToString());
            Response.Headers.Add("X-Content-Type-Options", "nosniff");

            var members = await _epmExportQueries.GetEmailAsync().ConfigureAwait(false);

            var csv = await _ggToolImport.CreateCSV(members).ConfigureAwait(false);

            return File(csv, "text/csv");

        }

        [HttpGet("directory")]
        public async Task<IActionResult> Directory()
        {

            // Response...
            System.Net.Mime.ContentDisposition cd = new System.Net.Mime.ContentDisposition
            {
                FileName = $"AgHallDirectory_{DateTime.Now:yyyyMMdd}.csv",
                Inline = false  // false = prompt the user for downloading;  true = browser to try to show the file inline
            };
            Response.Headers.Add("Content-Disposition", cd.ToString());
            Response.Headers.Add("X-Content-Type-Options", "nosniff");

            var members = await _epmExportQueries.GetDirectoryAsync().ConfigureAwait(false);


            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Occupants");
                var currentRow = 1;
                worksheet.Cell(currentRow, 1).Value = "Name";
                worksheet.Cell(currentRow, 2).Value = "Dept";
                foreach (var member in members)
                {
                    currentRow++;
                    worksheet.Cell(currentRow, 1).Value = member.Name;
                    worksheet.Cell(currentRow, 2).Value = member.Department;
                }

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();

                    return File(
                        content,
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        $"AgHallDirectory_{DateTime.Now:yyyyMMdd}.xlsx");
                }
            }

        }
    }
}

src/Web/Views/Shared/Components/MainMenu/MainMenuViewComponent.cs
using System;
using System.Threading.Tasks;
using AAE.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CALS.AgHallExport.Web.Shared.Components.MainMenu
{
    public class MainMenuViewComponent : ViewComponent
    {
        private readonly IHttpContextAccessor _contextAccessor;
        public MainMenuViewComponent(IHttpContextAccessor contextAccessor)
        {
            _contextAccessor = contextAccessor ?? throw new ArgumentNullException(nameof(contextAccessor));
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            // // EXAMPLE below if using an app-specific identity rather than the original/standard
            // var user = new CCLogUser(_contextAccessor.HttpContext.User.Identities.Where(i=>i.AuthenticationType == ThisAppUser.ThisAppAuthenticationType).FirstOrDefault());
            var user = new ClaimsApplicationUser(_contextAccessor.HttpContext.User);



            // wrapping it in an async call until there is something that actually async (like a DB call)
            return await Task.Run(() =>
            {
                var vm = new ViewModels.MainMenu()
                {
                    LoggedInUser = $"{user.FirstName} {user.LastName}"
                };

                return View(vm);
            });
        }
    }
}

src/Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "";
}

<div class="text-center mt-5">
    <a asp-action="Export" class="btn btn-primary btn-lg" target="_blank">Export Ag Hall EMAIL List <i class="fas fa-file-export"></i></a>
</div>

<div class="text-center mt-5">
    <a asp-action="Directory" class="btn btn-primary btn-lg" target="_blank">Export Ag Hall DIRECTORY List <i class="fas fa-file-export"></i></a>
</div>

src/Web/Views/Shared/Components/MainMenu/Default.cshtml
@model CALS.AgHallExport.Web.ViewModels.MainMenu
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <ul class="navbar-nav mr-auto">
        
    </ul>
<ul class="navbar-nav ml-auto nav-flex-icons">
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="javascript:;"><i class="fas fa-user"></i> @Model.LoggedInUser</a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="/Shibboleth.sso/Logout"><i class="fas fa-sign-out-alt"></i> Logout</a>
        </div>
    </li>
</ul>

src/Web/Views/Shared/_FavIcons.cshtml
<link rel="apple-touch-icon" sizes="180x180" href="~/img/favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="~/img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="~/img/favicon/favicon-16x16.png">
<link rel="manifest" href="~/img/favicon/site.webmanifest">
<link rel="mask-icon" href="~/img/favicon/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="~/img/favicon/favicon.ico">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="~/img/favicon/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

src/Web/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @await Html.PartialAsync("_Favicons")
    <title>@(string.IsNullOrEmpty(ViewBag.Title) ? "" : ViewBag.Title + " - ")@ViewBag.AppConfig.Branding</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link href="~/css/fontawesome.min.css" rel="stylesheet">
    <link href="~/css/solid.min.css" rel="stylesheet">

    @RenderSection("mastercss", required: false)
</head>
<body>


    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <div class="container d-flex justify-content-between">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars" aria-controls="navbars" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbars">
                @await Component.InvokeAsync("MainMenu")
            </div>
        </div>
    </nav>

    <div class="container mt-3">
        @RenderBody()
    </div>
    <!-- /.container -->

    <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; Copyright @DateTime.Now.Year, AAE IT Services Center</p>
    </footer>


    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>




    @RenderSection("masterjs", required: false)
</body>
</html>